name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  CONFIGURATION: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration "${{ env.CONFIGURATION }}" --no-restore

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore

      - name: Test
        run: dotnet test --configuration "${{ env.CONFIGURATION }}" --no-restore

  format:
    name: Format
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore

      - name: Verify formatting
        run: dotnet format ./HEAL.HeuristicLib.sln --verify-no-changes --no-restore --severity error

  pack:
    name: Pack
    runs-on: ubuntu-latest
    needs:
      - test
      - format

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore

      - name: Pack NuGet packages
        run: dotnet pack --configuration "${{ env.CONFIGURATION }}" --no-restore

      - name: Upload NuGet artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          name: nuget-packages
          path: ./src/**/bin/${{ env.CONFIGURATION }}/*.nupkg
          if-no-files-found: error
